default:
  image: python:3.8
  before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip install -r requirements.txt

stages:
  - test

test:
  script:
    - coverage run -m pytest
    - coverage report
