default:
  image: python:3.8
  before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip install -r requirements.txt

stages:
  - test
  - deploy

test:
  script:
    - coverage run -m pytest
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov/

deploy:
  dependencies:
    - test
  script:
    - mv htmlcov/ public/reports/coverage/
  artifacts:
    paths:
      - public
    expire_in: 1 week